version: '3'

services:
  web:
    build: .
    image: reimbursement-portal:v1.0
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_APP=run.py
      - SECRET_KEY=your-production-secret-key-change-me
    restart: always
